### ISSUE TITLE
Click on the `Take the survey` button doesn't take the user to the `Survey detail` screen

### ISSUE THREAD

**Issue by luongvo** [lydiasama/Survey#15]
Hi @lydiasama, I'm Lucas from Nimble. Nice to meet you here 👋 

I'll take care of reviewing your assignment and give you some feedback here from our side by opening issue tickets. Please feel free to catch up on this and help us know more about you by discussing and resolving the issues.

Firstly, you're doing well, the build is running smoothly and has a good ui 👌
But, when checking the app, I found that you seem misunderstood our criteria about showing and opening Survey detail
> The button “Take Survey” should take the user to a new screen. Simply implement the navigation.

**Comment by lydiasama** [comment]
Hi @luongvo , Nice to meet you and thank you very much for your time to review my code :)
about the requirement, I'm so sorry that I misunderstood about the 'Take a Survey' button

so this is the requirement here, 

>  The button “Take Survey” should take the user to a new screen. Simply implement the navigation.

I don't know about new screen should show the details and understood that new screen is just another page(another next item of list)

However, I will fix it soon!

**Comment by lydiasama** [comment]
I've fixed it in https://github.com/lydiasama/Survey/pull/28
