### ISSUE TITLE
Some issues in gradle and manifest config

### ISSUE THREAD

**Issue by luongvo** [lydiasama/Survey#16]
In app gradle build:
- I don't think to put dependency version inside `dependencies` block is a good idea. The definition of `kotlin_version` and `koinVersion` are not the same and consistency https://github.com/lydiasama/Survay/blob/master/app/build.gradle#L45
- It seems the config `testOptions.unitTests.includeAndroidResources` inside `dependencies` block doesn't work and seems to be right? 🤔  https://github.com/lydiasama/Survay/blob/master/app/build.gradle#L96
- There are some duplicated libs, e.g. `circleindicator`, `converter-gson`, `constraintlayout`, etc https://github.com/lydiasama/Survay/blob/master/app/build.gradle#L74

In Manifest:
- Do we need to go with different themes between the whole app config and each activity? I expect at least we only need different themes between Splash and Main screens? 🤓 
- There are invalid properties, e.g. [launchMode](https://github.com/lydiasama/Survay/blob/master/app/src/main/AndroidManifest.xml#L14), [screenOrientation](https://github.com/lydiasama/Survay/blob/master/app/src/main/AndroidManifest.xml#L16) at [application](https://developer.android.com/guide/topics/manifest/application-element)

**Comment by lydiasama** [comment]
In app gradle build; I fixed it in https://github.com/lydiasama/Survey/pull/24

**Comment by lydiasama** [comment]
About 

> Do we need to go with different themes between the whole app config and each activity? I expect at least we only need different themes between Splash and Main screens? 🤓

Yes, It is different theme between Splash and others screen.  because I implemented [SplashTheme](https://github.com/lydiasama/Survey/blob/6bf27fad34bc3cf45d78d04dd4ecbfe6c7b19944/app/src/main/AndroidManifest.xml#L22) for showing splash screen.

**Comment by lydiasama** [comment]
> There are invalid properties, e.g. launchMode, screenOrientation at application

I'm not sure what did you mean about invalid properties? I think it is ok to use. So if it's not good please feel free to suggest me :)

**Comment by luongvo** [comment]
> I'm not sure what did you mean about invalid properties? I think it is ok to use. So if it's not good please feel free to suggest me :)

@ly

**Comment by lydiasama** [comment]
> > I'm not sure what did you mean about invalid properties? I think it is ok to use. So if it's not good please feel free to suggest me :)
> 
> @lydiasama I meant I don't think we have `launchMode ` and `screenOrientation` at `application` tag config, it should belong to `activity` tag config

Fixed!  https://github.com/lydiasama/Survey/pull/27
