### ISSUE TITLE
The project's package structure could be better

### ISSUE THREAD

**Issue by luongvo** [lydiasama/Survey#17]
We see that you already tried to organize the project code by defining necessary components, separating the logic, and putting them in necessary packages. Even that, there is still something we could think about to improve more and more:

We need to separate all components a bit clearer and more independent by its function: networking, data, UI, etc. So I think we could try to optimize the current package structure to:
  + di (all DI parts here)
    + modules
  + models/data (model and dto)
  + services (network, API, authentication, interceptor, request/response)
  + UI
    + base (base widgets, base screen components, base viewmodel)
    + screens (main, detail and its VM)
  + util (the rest)

**Comment by lydiasama** [comment]
Actually, in very large project I prefer to manage the package by Feature such as Login, Splash, Survey, etc..  so in each Feature there are their own dataSource, module, api interface for their feature, model, etc.  It is good when we want to edit or maintain, It can go to the target class quickly and easily. 

But in this project I understand that my packages is inconsistency. some packages are on it own features, some on the common. I will try to improve it more.

**Comment by lydiasama** [comment]
@luongvo I've improved its package in https://github.com/lydiasama/Survey/pull/31
