### ISSUE TITLE
No mechanism to cache the access token to the next app session

### ISSUE THREAD

**Issue by luongvo** [lydiasama/Survey#18]
I'm not convinced of the way you handle the AccessToken getting/saving by just keeping it in the app session memory https://github.com/lydiasama/Survay/blob/master/app/src/main/java/com/lydiasama/survay/authentication/token/AccessToken.kt#L4. 

That means we have to request the new access token whenever we start the app again? 🤔

**Comment by lydiasama** [comment]
Fixed in https://github.com/lydiasama/Survey/pull/29

**Comment by lydiasama** [comment]
Fixed in https://github.com/lydiasama/Survey/pull/30
