### ISSUE TITLE
Should we find another way to keep app credentials?

### ISSUE THREAD

**Issue by luongvo** [lydiasama/Survey#20]
Currently, I see you put all authentication credentials at [AuthenticationRequest](https://github.com/lydiasama/Survay/blob/master/app/src/main/java/com/lydiasama/survay/authentication/data/AuthenticationRequest.kt) that contains an initial username and password. Basically we should not put any credentials in the code and try to extract out as config. Can you propose a way to get rid of this issue?

**Comment by lydiasama** [comment]
Fixed in #29
